/**
 * generatePdf — Place Brief PDF report generator for Transitus.
 *
 * WHAT: Produces a professional briefing-style PDF for a given Place,
 *       including burdens, commitments, field notes, signals, and stakeholders.
 * WHERE: Called from Place Detail page or Reports section.
 * WHY: Field companions and stewards need offline briefs to share
 *       with community partners, funders, and institutional stakeholders.
 */

import jsPDF from 'jspdf';
import type {
  Place,
  Commitment,
  FieldNote,
  Signal,
  Stakeholder,
  EnvironmentalBurden,
} from '@/types/transitus';
import {
  ROLE_LABELS,
  COMMITMENT_STATUS_LABELS,
  SIGNAL_SOURCE_LABELS,
} from '@/types/transitus';

// ── Layout constants ──

const PAGE_FORMAT = 'letter' as const;
const UNIT = 'pt' as const;
const MARGIN = 50;
const LINE_HEIGHT = 15;
const SECTION_GAP = 28;

// ── Color palette (earth tones) ──

const COLORS = {
  title: [30, 22, 18] as [number, number, number],         // deep umber
  heading: [120, 72, 48] as [number, number, number],       // terracotta
  subheading: [80, 65, 55] as [number, number, number],     // warm gray
  body: [50, 45, 40] as [number, number, number],           // charcoal
  muted: [130, 120, 110] as [number, number, number],       // parchment gray
  divider: [210, 200, 190] as [number, number, number],     // light parchment
  accent: [22, 101, 52] as [number, number, number],        // forest
};

const SEVERITY_LABELS: Record<EnvironmentalBurden['severity'], string> = {
  critical: 'CRITICAL',
  high: 'HIGH',
  moderate: 'MODERATE',
  low: 'LOW',
};

// ── Helpers ──

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}

function truncate(text: string, maxLen: number): string {
  if (text.length <= maxLen) return text;
  return text.slice(0, maxLen - 3).trimEnd() + '...';
}

// ── Main export ──

export async function generatePlaceBriefPdf(
  place: Place,
  commitments: Commitment[],
  fieldNotes: FieldNote[],
  signals: Signal[],
  stakeholders: Stakeholder[],
): Promise<void> {
  const doc = new jsPDF({ unit: UNIT, format: PAGE_FORMAT });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const contentW = pageW - MARGIN * 2;
  let y = MARGIN;

  // ── Utility: page management ──

  function addPage() {
    addFooter();
    doc.addPage();
    y = MARGIN;
  }

  function checkPage(need: number) {
    if (y + need > pageH - MARGIN - 20) addPage();
  }

  function addFooter() {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.muted);
    doc.text(
      'Generated by Transitus — The Operating System for Places Under Change',
      pageW / 2,
      pageH - 25,
      { align: 'center' },
    );
  }

  function drawDivider() {
    doc.setDrawColor(...COLORS.divider);
    doc.setLineWidth(0.5);
    doc.line(MARGIN, y, pageW - MARGIN, y);
    y += 12;
  }

  function addSectionTitle(title: string) {
    checkPage(40);
    y += SECTION_GAP;
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.heading);
    doc.text(title.toUpperCase(), MARGIN, y);
    y += 6;
    drawDivider();
    y += 4;
  }

  function addBodyText(text: string, indent = 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.body);
    const lines = doc.splitTextToSize(text, contentW - indent);
    for (const line of lines) {
      checkPage(LINE_HEIGHT);
      doc.text(line, MARGIN + indent, y);
      y += LINE_HEIGHT;
    }
  }

  function addLabelValue(label: string, value: string, indent = 0) {
    checkPage(LINE_HEIGHT);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...COLORS.subheading);
    doc.text(`${label}:`, MARGIN + indent, y);
    const labelWidth = doc.getTextWidth(`${label}: `);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...COLORS.body);
    const valueLines = doc.splitTextToSize(value, contentW - indent - labelWidth - 5);
    doc.text(valueLines[0], MARGIN + indent + labelWidth + 3, y);
    y += LINE_HEIGHT;
    // additional wrapped lines
    for (let i = 1; i < valueLines.length; i++) {
      checkPage(LINE_HEIGHT);
      doc.text(valueLines[i], MARGIN + indent + labelWidth + 3, y);
      y += LINE_HEIGHT;
    }
  }

  // ═══════════════════════════════════════════════════
  // TITLE BLOCK
  // ═══════════════════════════════════════════════════

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.muted);
  doc.text('TRANSITUS', MARGIN, y);
  y += 20;

  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...COLORS.title);
  const titleLines = doc.splitTextToSize(place.name, contentW);
  for (const line of titleLines) {
    doc.text(line, MARGIN, y);
    y += 30;
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...COLORS.heading);
  doc.text('Monthly Brief', MARGIN, y);
  y += 24;

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  doc.text(`Generated ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, MARGIN, y);
  y += 8;
  doc.text(`${place.geography}  |  ${place.lat.toFixed(4)}°N, ${Math.abs(place.lng).toFixed(4)}°${place.lng >= 0 ? 'E' : 'W'}`, MARGIN, y);
  y += 16;

  drawDivider();

  // ═══════════════════════════════════════════════════
  // 1. PLACE OVERVIEW
  // ═══════════════════════════════════════════════════

  addSectionTitle('Place Overview');

  addBodyText(place.description);
  y += 8;

  if (place.communities.length > 0) {
    addLabelValue('Communities', place.communities.join(', '));
  }
  if (place.population_estimate) {
    addLabelValue('Population Estimate', place.population_estimate.toLocaleString('en-US'));
  }
  addLabelValue('Geography', place.geography);
  if (place.land_use.length > 0) {
    addLabelValue('Land Use', place.land_use.join(', '));
  }
  if (place.key_institutions.length > 0) {
    addLabelValue('Key Institutions', place.key_institutions.join(', '));
  }
  if (place.transition_issues.length > 0) {
    addLabelValue('Transition Issues', place.transition_issues.join('; '));
  }

  // ═══════════════════════════════════════════════════
  // 2. ENVIRONMENTAL BURDENS
  // ═══════════════════════════════════════════════════

  if (place.environmental_burdens.length > 0) {
    addSectionTitle('Environmental Burdens');

    for (const burden of place.environmental_burdens) {
      checkPage(45);
      // Name + severity inline
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.body);
      doc.text(burden.name, MARGIN + 4, y);
      const nameWidth = doc.getTextWidth(burden.name + '  ');
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(
        burden.severity === 'critical' ? 180 : burden.severity === 'high' ? 190 : 120,
        burden.severity === 'critical' ? 40 : burden.severity === 'high' ? 80 : 100,
        burden.severity === 'low' ? 60 : 40,
      );
      doc.text(`[${SEVERITY_LABELS[burden.severity]}]`, MARGIN + 4 + nameWidth, y);
      y += LINE_HEIGHT;

      // Description
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.body);
      const descLines = doc.splitTextToSize(burden.description, contentW - 12);
      for (const line of descLines) {
        checkPage(LINE_HEIGHT);
        doc.text(line, MARGIN + 12, y);
        y += LINE_HEIGHT - 2;
      }

      // Source
      if (burden.source) {
        doc.setFontSize(8);
        doc.setTextColor(...COLORS.muted);
        doc.text(`Source: ${burden.source}`, MARGIN + 12, y);
        y += LINE_HEIGHT - 2;
      }
      y += 6;
    }
  }

  // ═══════════════════════════════════════════════════
  // 3. ACTIVE COMMITMENTS
  // ═══════════════════════════════════════════════════

  if (commitments.length > 0) {
    addSectionTitle('Active Commitments');

    for (const c of commitments) {
      checkPage(40);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.body);
      doc.text(`• ${truncate(c.title, 70)}`, MARGIN + 4, y);
      y += LINE_HEIGHT;

      addLabelValue('Status', COMMITMENT_STATUS_LABELS[c.status], 12);

      if (c.context) {
        doc.setFontSize(9);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(...COLORS.body);
        const contextLines = doc.splitTextToSize(truncate(c.context, 200), contentW - 16);
        for (const line of contextLines) {
          checkPage(LINE_HEIGHT);
          doc.text(line, MARGIN + 16, y);
          y += LINE_HEIGHT - 2;
        }
      }

      if (c.renewal_date) {
        addLabelValue('Review Date', formatDate(c.renewal_date), 12);
      }
      y += 4;
    }
  }

  // ═══════════════════════════════════════════════════
  // 4. RECENT FIELD NOTES
  // ═══════════════════════════════════════════════════

  const recentNotes = fieldNotes
    .sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
    .slice(0, 5);

  if (recentNotes.length > 0) {
    addSectionTitle('Recent Field Notes');

    for (const note of recentNotes) {
      checkPage(35);
      const noteTypeLabel = note.note_type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
      doc.setFontSize(9);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.subheading);
      doc.text(`${noteTypeLabel} — ${formatDate(note.created_at)}`, MARGIN + 4, y);
      y += LINE_HEIGHT;

      addBodyText(truncate(note.content, 300), 12);

      if (note.what_changed) {
        addLabelValue('What Changed', truncate(note.what_changed, 150), 12);
      }
      if (note.follow_up) {
        addLabelValue('Follow-up', truncate(note.follow_up, 150), 12);
      }
      y += 4;
    }
  }

  // ═══════════════════════════════════════════════════
  // 5. RECENT SIGNALS
  // ═══════════════════════════════════════════════════

  const recentSignals = signals
    .sort((a, b) => new Date(b.published_at).getTime() - new Date(a.published_at).getTime())
    .slice(0, 5);

  if (recentSignals.length > 0) {
    addSectionTitle('Recent Signals');

    for (const signal of recentSignals) {
      checkPage(35);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.body);
      doc.text(`• ${truncate(signal.title, 70)}`, MARGIN + 4, y);
      y += LINE_HEIGHT;

      const sourceName = SIGNAL_SOURCE_LABELS[signal.source] ?? signal.source;
      addLabelValue('Source', `${sourceName} — ${formatDate(signal.published_at)}`, 12);

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.body);
      const summaryLines = doc.splitTextToSize(truncate(signal.summary, 250), contentW - 16);
      for (const line of summaryLines) {
        checkPage(LINE_HEIGHT);
        doc.text(line, MARGIN + 16, y);
        y += LINE_HEIGHT - 2;
      }
      y += 6;
    }
  }

  // ═══════════════════════════════════════════════════
  // 6. KEY STAKEHOLDERS
  // ═══════════════════════════════════════════════════

  if (stakeholders.length > 0) {
    addSectionTitle('Key Stakeholders');

    for (const person of stakeholders) {
      checkPage(30);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(...COLORS.body);
      doc.text(`• ${person.name}`, MARGIN + 4, y);

      const nameWidth = doc.getTextWidth(`• ${person.name}  `);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(...COLORS.muted);
      doc.text(`(${ROLE_LABELS[person.role]})`, MARGIN + 4 + nameWidth, y);
      y += LINE_HEIGHT;

      if (person.title) {
        addLabelValue('Title', person.title, 12);
      }
      if (person.trust_level) {
        addLabelValue('Relationship', person.trust_level.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()), 12);
      }
      if (person.last_contact) {
        addLabelValue('Last Contact', formatDate(person.last_contact), 12);
      }
    }
  }

  // ── Footer on last page ──
  addFooter();

  // ── Save ──
  const safeFileName = place.name.replace(/[^a-zA-Z0-9 ]/g, '').replace(/\s+/g, '-').toLowerCase();
  doc.save(`${safeFileName}-monthly-brief.pdf`);
}
